apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3310      # Hizmetin dış dünyaya açık olduğu port
      targetPort: 3306  # MySQL sunucusunun dinlediği port
  type: ClusterIP